export const MYPAGE_POST = "MYPAGE/MYPAGE_POST";
export const MYPAGE_POST_SUCCESS = "MYPAGE/MYPAGE_POST_SUCCESS";
export const MYPAGE_POST_FAIL = "MYPAGE/MYPAGE_POST_FAIL";

export const MYPAGE_PWCHECK = "MYPAGE/MYPAGE_PWCHECK";
export const MYPAGE_PWCHECK_SUCCESS = "MYPAGE/MYPAGE_PWCHECK_SUCCESS";
export const MYPAGE_PWCHECK_FAIL = "MYPAGE/MYPAGE_PWCHECK_FAIL";

export const MYPAGE_PWCHECK_CHANGE = "MYPAGE/MYPAGE_CHANGE";
export const MYPAGE_PWCHECK_CHANGE_SUCCESS = "MYPAGE/MYPAGE_CHANGE_SUCCESS";
//export const MYPAGE_PWCHECK_CHANGE_FAIL = "MYPAGE/MYPAGE_CHANGE_FAIL";

export const MYPAGE_UPDATE_MYINFO = "MYPAGE/MYPAGE_UPDATE_MYINFO";
export const MYPAGE_UPDATE_SUCCESS = "MYPAGE/MYPAGE_UPDATE_MYINFO_SUCCESS";

export const MYPAGE_UPDATE_MYINFO_CHANGE = "MYPAGE/MYPAGE_UPDATE_MYINFO_CHANGE";
export const MYPAGE_UPDATE_MYINFO_CHANGE_SUCCESS =
  "MYPAGE/MYPAGE_UPDATE_MYINFO_CHANGE_SUCCESS";
