export const BOARD_POST = "MAINBOARD/BOARD_POST";
export const BOARD_POST_FAIL = "MAINBOARD/BOARD_POST_FAIL";
export const BOARD_POST_SUCCESS = "MAINBOARD/BOARD_POST_SUCCESS";

export const INIT = "MAINBOARD/INIT";